### ISSUE TITLE
提取数据

### ISSUE THREAD

**Issue by xubogithub** [weisongwen/UrbanNavDataset#1]
你好，我想从rosbag中提取出来groundtruth的经、纬、高等数据，请问下需要怎么提取呢

**Comment by DarrenWong** [comment]
For retrieving the ground truth data collected by SPAN-CPT (topics: /novatel_data/inspvax),
1. save all the data directly into csv files ( change YOUR_BACK_FILENAME to the actual bag name), it might need some times,
`rostopic echo -b $YOUR_BACK_FILENAME  -p /novatel_data/inspvax > grount_truth.csv
`
2. subscribe the topic **/novatel_data/inspvax** with [novatel_msgs](http://wiki.ros.org/novatel_msgs) while you are playing back the contents orosbag ,
`rosbag play $YOUR_BACK_FILENAME`

**Comment by xubogithub** [comment]
谢谢您
