### ISSUE TITLE
some question about extrinsic

### ISSUE THREAD

**Issue by noobslamer** [weisongwen/UrbanNavDataset#11]
I would like to ask is there information about lever arms between IMU and GNSS antenna to offer?It would be perfect if you can offer that and thanks for your time.

**Comment by DarrenWong** [comment]
Thanks for your question. Sorry that we do not have the lever arm between the IMU and GNSS antenna. Normally we place the antenna around 50 cm front or rear part of the vehicle roof. We are going to release more dataset in the coming months (https://www.ion.org/gnss/abstracts.cfm?paperID=10318) which include the details of the extrinsic between the GNSS and IMU.
