### ISSUE TITLE
Accuracy of the lidar-camera calibration

### ISSUE THREAD

**Issue by BayRanger** [weisongwen/UrbanNavDataset#14]
Hi,
Currently I am doing some lidar reprojection on the image plane, but there seems to a misalignment  betweeen the two frames, one potential reason would be the inaccurate calibration... Therefore, I'd like to ask about the accuracy level of the camera lidar calibration....
![Screenshot from 2021-09-20 11-35-13](https://user-images.githubusercontent.com/52582044/133982071-815fae3a-36b1-4a6b-b05c-e6ee47f4e141.png)

**Comment by DarrenWong** [comment]
Thanks for using the dataset. Assume you are using the 20200314:
The calibration between Lidar-IMU is determined by direct in-situ measurements (the rotation part is approximately identity matrix + z-axis offset 28cm, Lidar is above ), the accuracy level is around ±5cm
Camera Intrinsic: using Kalibr 
The calibration between camera-IMU is determined by Kalibr 

The Lidar reprojection to the image is an interesting topic but we don't test it yet. We can check if you can share more details of how to do the projection. For example some KITTI-related tools? Should change the scan line 64 to 32, and the FOV is a little different between HDL64 and HDL32.
