### ISSUE TITLE
The orientation of x, y for Lidar.

### ISSUE THREAD

**Issue by JunyuanDeng** [weisongwen/UrbanNavDataset#16]
When I use pcl_viewer to present the pointcloud of one frame (.pcd file) and I use command: pcl_viewer 1556456384.020306000.pcd -ax 10. I found that the orientation of x towards to the back of the car, but in ![platform figure](https://github.com/weisongwen/UrbanNavDataset/blob/master/img/hongkong_sensor.png), orientation of x towards to the head of the car. Is there something wrong here?
![Pointcloud](https://user-images.githubusercontent.com/62542727/136473989-dcdad6bc-2e9e-4d86-a18a-39b76a50f509.png)

**Comment by DarrenWong** [comment]
Yes, the pcl_viewer is correct if you are using data 20190428. The LiDAR is installed in a different location as x pointing in the rear of the vehicle and y to the right of the vehicle. 

Sorry that the platform image is outdated. For more details, please refer to the extrinsic data https://github.com/weisongwen/UrbanNavDataset/blob/master/UrbanNav-HK-Data20190428/extrinsic.yaml

For other data, y-axis pointing in the direction of travel, x-axis to the right
