### ISSUE TITLE
UrbanNav-HK-Data20190428 的数据集 不同gps信号怎么区分

### ISSUE THREAD

**Issue by xyj1991** [weisongwen/UrbanNavDataset#18]
UrbanNav-HK-Data20190428 的数据集中有三种gps的topic，简介里是有rtk和gps ，novatel_data是rtk的，ublox_node是gps的  那 navsat是什么信号      /navsat/fix  /novatel_data/inspvax     /ublox_node/fix

**Comment by xyj1991** [comment]
UrbanNav-HK-Data20190428 [的数据集中rtk的数据，有信号优劣的参数吗，类似与GPGGA中会有gps的状态和卫星数量来作为信号稳定的数据  
字段6：GPS状态，0=未定位，1=非差分定位，2=差分定位，3=无效PPS，6=正在估算

字段7：正在使用的卫星数量（00 - 12）（前导位数不足则补0）

**Comment by DarrenWong** [comment]
The ground truth ( **/novatel_data/inspvax**) provides flags (INS Status and Pos Type) to indicate the solution quality, http://docs.ros.org/en/jade/api/novatel_msgs/html/msg/INSPVAX.html.
