### ISSUE TITLE
the groundtruth

### ISSUE THREAD

**Issue by yongguixu** [weisongwen/UrbanNavDataset#20]
Hello, can you provide the groundtruth with a high frequency?

**Comment by DarrenWong** [comment]
Sorry that we do not have a high-frequency GT as we collect the 1hz ground truth with the ROSBAG in real-time in this dataset. 

What frequency do you need? We release some [new data](https://github.com/IPNL-POLYU/UrbanNavDataset) in 2021 which can produce higher-frequency (such as 10hz) GT with post-processing.

**Comment by weisongwen** [comment]
feel free to re-open if needed :-)
