### ISSUE TITLE
About ground truth

### ISSUE THREAD

**Issue by zhanglei1997** [weisongwen/UrbanNavDataset#22]
Hello, I also noticed another paper of yours:
Point-wise or Feature-wise? Benchmark Comparison of Public Available LiDAR Odometry Algorithms in Urban Canyons.
For the experimental part of this paper, you used two sequences that were previously made in Hong Kong. I would like to know how you used the EVO tool to get the ground truth from the bag and compare it with all the other algorithm results.
Looking forward to your reply.

**Comment by zhanglei1997** [comment]
![image](https://user-images.githubusercontent.com/54139666/171111309-8bdcdaa0-6d89-4f26-b0ed-74fbd20bae07.png)

**Comment by DarrenWong** [comment]
closed as same issue here: https://github.com/IPNL-POLYU/UrbanNavDataset/issues/18
