### ISSUE TITLE
imu axis

### ISSUE THREAD

**Issue by Lunar871** [weisongwen/UrbanNavDataset#24]
Thank you for the open source dataset , may i know how is the IMU installed for the Tokyo dataset?

**Comment by weisongwen** [comment]
@DarrenWong Hi darren, can you please kindly help with this? thanks

**Comment by DarrenWong** [comment]
Hi, thank you for your interest in our dataset.

As [mentioned]( https://github.com/weisongwen/UrbanNavDataset#2-tokyo-dataset) in the readme that,
`Important Notes: the LiDAR calibration file for the LiDAR sensor, extrinsic parameters between sensors are not available now. If you wish to study the GNSS/LiDAR/IMU integration, we suggest using the dataset above collected in Hong Kong. However, the GNSS dataset from Tokyo is challenging which is collected in challenging urban canyons!
`
Suggest you use the Hong Kong dataset for the multi-sensor integration
