### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jesseyangonly1** [weisongwen/UrbanNavDataset#27]
Hello, I have a question about the fisheye camera. I didn't find the fisheye view in the bag.

**Comment by DarrenWong** [comment]
The fish eye should be collected in the urbanloco dataset. https://github.com/weisongwen/UrbanLoco

But we also have some self-collected datasets that use the fisheye camera with UrbanNav dataset setup, you can use the below link if you are interested. 
https://www.dropbox.com/scl/fo/yye97cpwtxxo0ktwxkjog/h?rlkey=av09k6y8yk0wmdn10o2t2glny&dl=0

**Comment by jesseyangonly1** [comment]
> The fish eye should be collected in the urbanloco dataset. https://github.com/weisongwen/UrbanLoco
> 
> But we also have some self-collected datasets that use the fisheye camera with UrbanNav dataset setup, you can use the below link if you are interested. https://www.dropbox.com/scl/fo/yye97cpwtxxo0ktwxkjog/h?rlkey=av09k6y8yk0wmdn10o2t2glny&dl=0

Thank you!
