### ISSUE TITLE
数据解压问题

### ISSUE THREAD

**Issue by cll-git** [weisongwen/UrbanNavDataset#30]
您好，请问百度网盘下载的UrbanNav-HK_Whampoa-20210521_sensors.zip和UrbanNav-HK_Whampoa-20210521_sensors.z01应该怎么解压呢？

**Comment by DarrenWong** [comment]
你好，可以用7z x UrbanNav-HK_Whampoa-20210521_sensors.zip 命令来解压

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/68edc0f4-9d3b-4724-a071-1e332380bad7">

**Comment by cll-git** [comment]
好的，十分感谢。
