### ISSUE TITLE
IMU calibration

### ISSUE THREAD

**Issue by xubogithub** [weisongwen/UrbanNavDataset#4]
I used imu data and image data to run vins ,the parameter file need imu bias and noise, I don't find four parameters , I also try to calibrate the imu data ,howerer, It need static and the data must  continue two hours ,so I wonder where can I find the imu bias and noise parameter ,thank you

**Comment by DarrenWong** [comment]
Please refer to [imu noise](https://github.com/weisongwen/UrbanNavDataset/blob/master/UrbanNav-HK-Data20190428/xsens_imu_param.yaml) we just uploaded. 
We collected 2 hrs data then process with [imu_utils](https://github.com/gaowenliang/imu_utils)

**Comment by xubogithub** [comment]
thank you very much
