### ISSUE TITLE
IMU parameter

### ISSUE THREAD

**Issue by xiaoshitou4** [weisongwen/UrbanNavDataset#7]
Hi:
     I cann't find the IMU parameter about Toyko dataset, for example ARW,VRW and so on. It would be better if the lever arm betweeen different sensor could be provided

Thk !

**Comment by DarrenWong** [comment]
The IMU parameters of Toyko are not available now. If you wish to study the GNSS/LiDAR/IMU integration, we suggest using the dataset above collected in Hong Kong.
https://github.com/weisongwen/UrbanNavDataset#22-dataset-1-urbannav-tk-20181219
