### ISSUE TITLE
ground_truth

### ISSUE THREAD

**Issue by Liming-Cheng** [weisongwen/UrbanNavDataset#9]
How can I get the ground_truth from novatel_msgs/INSPVAX?
There seems no timestamp, can you provide the ground_truth file for dataset?
Thank you very much!

**Comment by DarrenWong** [comment]
Dear Cheng,

You can use the GPS time in the  novatel_msgs/INSPVAX to get a precious timestamp
```
uint16 gps_week
uint32 gps_week_seconds
```
http://docs.ros.org/en/jade/api/novatel_msgs/html/msg/CommonHeader.html
If you are working on ROS, you can record an approximate ROS timestamp when receiving a lidar/IMU ROS timestamp
